#+title: Simple IDE model simulation
#+PROPERTY: header-args :results silent

* Initial parameters

The =nodes= value is like the step size for space.

- Why do we need a radius and diameter?
- What is the =lowval= variable for?

The function =linspace(x1, x2, n)= creates an evenly spaced vector of =n= points between =x1= and =x2=

#+begin_src matlab :tangle simple_ide.m
clc

generations = 30;
lowval = 1e-14;
nodes = (2^10) + 1;
diameter = 1200;
radius = diameter / 2;
x = linspace(-radius, radius, nodes);
x2 = linspace(-diameter, diameter, 2*nodes-1);
dx = diameter / (nodes - 1);
n = zeros(generations+1, length(x)); % density
[spd_inst, spd_avg] = deal(zeros(1, generations));

#+end_src

We have to define our starting locations and their corresponding population densities. Since =x= is a range of locations from -600 to 600, we want to start out right in the center. We set =temp= to be the columns where =x= is between -5 and 5 (0 is column 513).

We set our starting population densities at these locations using the =normpdf()= function.

The variable =xright= holds the front location (/Is this necessary for our simplified model?/). After each iteration, the =interp1()= function adds the next front position.

#+begin_src matlab :tangle simple_ide.m
irad = 5;       % Initial condition range
idens = 2.0;      % Initial condition density maximum
ncrit = 0.05;   % critical threshold for edge of wave

% SET THE INITIAL CONDITIONS
temp = find(abs(x) <= irad);
n(1,temp) = idens*normpdf(x(temp),0,1);

% FIND THE INITIAL FRONT LOCATION
jj = find(n(1,:) >= ncrit,1,'last');
if jj
  xright(1) = interp1(n(1,jj:jj+1),x(jj:jj+1),ncrit);
end

#+end_src

* Dispersal kernel

Here we define our [[id:af5517ea-a453-4264-9619-49a523c34f2e][dispersal kernel]]; this is a Gaussian kernel. Equation taken from [cite:@lutscherIntegrodifferenceEquationsSpatial2019].

#+begin_src matlab :tangle simple_ide.m

% Gaussian kernel

sigma_sq = 0.25; % dispersal variance
k = exp(-(x2).^2/2*sigma_sq) ./ sqrt(2*pi*sigma_sq);

#+end_src

* Growth function

Here we define our growth function, using the Ricker growth model. Taken from [cite:@lutscherIntegrodifferenceEquationsSpatial2019].

Variable =n1= is the population density at time /t + 1/ ($N_{t+1}$). To find it, we perform the convolution of /k/ and /f/.

#+begin_src matlab :tangle simple_ide.m

%For Fig 1a:
r = 0.9;      % Ricker growth

for i = 1:generations
% Ricker growth function
f = (n(i,:)>=a).*n(i,:) .* exp(r*(1-n(i,:)));

% dispersal phase
n1 = fft_conv(k, f);
n(i+1, :) = dx * n1(nodes:length(x2));
end
#+end_src

* Plot

Plot is generated using the =plot3= function. The fourth argument is line color.

- There are two lines plotted.
      - The black (='k'=) line shows
      - The blue line (='b'=) shows

#+begin_src matlab :tangle simple_ide.m

%% Figure panel 1a - COMPENSATORY NO ALLEE

	[xx,tt] = meshgrid(x,0:generations);
	nlow = n;
	nlow(n>=ncrit) = NaN;
	n(n<ncrit) = NaN;
	hold on
	for i = 1:11
	     plot3(xx(i,:),tt(i,:),n(i,:),'b');
	     plot3(xx(i,:),tt(i,:),nlow(i,:),'Color',0.8*[1 1 1]);
	     grid on
	end
	plot3(xright(1:11),0:10,ncrit*ones(1,11),'k')
    axis([-15 15 0 10 0 1.5]);
    xlabel('space (x)');
    ylabel('time (t)');
    zlabel('density (n)');
    view(30,30);

#+end_src
